
POST http://localhost:3001/api/login
Content-Type: application/json


{
    "username":"rizaman",
    "password":"rizaman"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json


{
    "username":"rizaman",
    "password":"rizaman"
}